modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "modid"
version = "${version}"
displayName = "Example Mod"
description = "A Minecraft mod"
authors = "Your Name"
logoFile = "assets/modid/icon.png"

[[dependencies.modid]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.modid]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"
